server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #服务器数据库配置
    url: jdbc:mysql://82.157.124.157:3306/csrp?serverTimezone=GMT%2b8&useServerPrepStmts=TRUE&cachePrepStmts=TRUE
    username: root
    password: sdu_csrp
    #本地数据库配置
#    url: jdbc:mysql://localhost:3306/csrp?serverTimezone=GMT%2b8&useServerPrepStmts=TRUE&cachePrepStmts=TRUE
#    username: root
#    password: 486419lc

  # size
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  ## jsp
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
